#!/usr/bin/env bash
# Bash script that displays the content of the current directory
# In a list format where only the part of the name after the first dash is displayed

list=$(ls)
i="1"
for i in $list; do
	echo "$i" | cut -d '-' -f 2
done
